language: csharp

sudo: required  # use the new container-based Travis infrastructure

before_script:
 - chmod +x build.sh
 - chmod a+x travis-install-eibd.sh
 - ./travis-install-eibd.sh

script:
 - ./build.sh All
